### ISSUE TITLE
프로토타입 API 명세 확인 요망

### ISSUE THREAD

**Issue by songyoungsub** [ajantang/1-FavoritePhoto-1-BE#1]
## 요청 사항
현재 스키마와 일부 API 명세를 정리했는데 시간되시면 확인 부탁드립니다.

## 참고사항
path를 어떻게 지정할지 몰라 일단 비워 두었으며 
정리한 API는 프로젝트 요구 사항에서 포토 카드 거래 - 내 포토 카드 판매까지 정리했습니다.
참고로 포토 카드 등록 API도 정리했습니다.

## 참고 자료
노션 https://www.notion.so/API-11a3c19d1a2f804d8713d7b0b4691aec
중급 프로젝트 https://www.codeit.kr/topics/fs-intermediate-project-overview/lessons/10778?topicVersion=1&lessonVersion=1

**Comment by ajantang** [comment]
post 포토카드 등록

p1. 이미지를 등록하는 로직을 어떻게 할지 얘기해보죠.
 
1. image upload 를 별도의 api로 제공(아예 서버를 나누는 것도 가능) 
2. 미들웨어로 image upload를 서버에서 처리

제 생각엔 header에 content type 설정 때문에 별도로 관리해야할거 같은데, 그러면 post 포토카드 등록에 image는 url 을 넣어줘야 되요

참고 : 주말에 google cloud로 이미지 업로드 테스트 해봤는데, 잘 되네요. aws 테스트 해보셨으면 둘 중에 하나 골라서 하면 좋겠어요. 아니면, 두 개 다 코드 짜서 하나는 실패 시 서브로 실행하게 하면  좋겠어요.

**Comment by ajantang** [comment]
공통

p1. 제가 template에 type으로 해뒀는데, method가 더 좋은 명칭 같아요.
p1. 예시가 필요해 보여요. req exmple, res example
p3. image 속성으로 주고 받는거 전부 url 인지 확인 부탁드려요

**Comment by ajantang** [comment]
GET 상점 목록 조회

p1. 필터는 1개만 적용할건지 상의해보
p2. keyword와 soldout 으로 소문자로 하시죠
p2. 페이지네이션으로 하죠(cursor 삭제)
p2. query에 ownerId(또는 sellerId)를 추가하시죠. 피그마에 카드에 판매자 아이디를 클릭할 수 있는거 처럼 보였어요
p1. userName -> userNickname 으로 변경하죠. 가입할 때 닉네임으로 기입합니다. 판매자 닉네임으로 정의하시죠

user에도 비슷한 구조로 get하는 api가 있습니다.
## GET /users/my-cards

저랑 상의해서 확정지어보죠

**Comment by ajantang** [comment]
GET 내 포토카드 목록 조회

혹시 GET /users/my-card api 명세인가요?
필터랑 정렬 관련 쿼리가 부족해보입니다.

**Comment by ajantang** [comment]
GET 내 포토카드 상세

😊
