### ISSUE TITLE
해당 상점에 카드 수량(잔여량) + 보유량을 확인 API

### ISSUE THREAD

**Issue by ajantang** [ajantang/1-FavoritePhoto-1-BE#25]
## 어떤 기능인가요?

> 상점 수정 페이지 호출 시 판매 가능 수량(잔여량 + 보유량)을 확인할 수 있는 API 필요합니다

## 작업 상세 내용

- shopId를 기준으로 해당 상점에 올라간 card의 잔여량 + 보유량 정보 제공

## 참고할만한 자료(선택)
![image](https://github.com/user-attachments/assets/46dadf33-15ad-426a-82e4-3d5382d5c65f)

**Comment by songyoungsub** [comment]
확인했습니다. 
추후 상점 상세 API에  판매 가능 수량(잔여량 + 보유량)을 나타내는 response를 추가할 예정입니다.

**Comment by ajantang** [comment]
> 확인했습니다. 추후 상점 상세 API에 판매 가능 수량(잔여량 + 보유량)을 나타내는 response를 추가할 예정입니다.

알겠습니다.

상세 상점 정보를 제공하는 API에서 제공하는 것도 좋지만, 제 생각엔 별도로 제공하는 것도 좋아 보입니다. 저 모달창을 열 때 다시 상세 상점 정보를 모두 받아올 필요는 없어보여서요
