### ISSUE TITLE
교환 관련 response property 변경

### ISSUE THREAD

**Issue by ajantang** [ajantang/1-FavoritePhoto-1-BE#49]
## 어떤 기능인가요?

> 교환 신청(그 외 교환 관련 response 확인 필요)

## 작업 상세 내용

- 교환 신청 후 받는 id 정보가 교환id를 받아와야 합니다. 주체가 교환이니까요

## 참고할만한 자료(선택)
- 현재 구현 상황
![image](https://github.com/user-attachments/assets/0e389263-487a-4626-9e7d-a3f95b4f4c17)

**Comment by songyoungsub** [comment]
확인했습니다
함수 수정하며 같이 수정하겠습니다
